Add support for the clang compiler on Windows (v18)
crud89/LiteFX pull request #138
Opened 2024-08-10 08:04 UTC by Tractorou24

**Describe the pull request**  
This adds support for compiling the engine using the latest clang compiler (v18).  
This is a good step for more adoption, since not all projects only use msvc.  
It will also help porting to linux, since clang is stricter and more standard compliant, which will ease the compilation with GCC.  
I was not able to test CI changes, so you may need to run it on the branch, and I will fix it without any problem!

**Related issues**  
There are currently none, but I can create one if needed.

**A word for you**  
First, I would like to thank you for this awesome project. It's just the best rendering engine I could find using modern C++!
I made some changes here I'm not a fan with (removing some constexprs). As much as I love those things, they are just not possible, and msvc just allows it wrongfully.  
Thank you also for the time you take to read this, and review this if you are interested in it!

2024-08-13 12:43 UTC, crud89 commented
Thank's a lot for the PR and the kind words! 🙂 Unfortunately I am a little bit busy at the moment, but I will go through the changes as soon as I find time for it. 

With regards to Linux, I have a branch for WSL-support. Unfortunately I could not get GCC to work with stacktrace yet, which I (maybe overhasty) added to the exceptions. Also WSL has this annoying bug, where it does not work if the filesystem is split over multiple physical drives, which is my setup on both systems I have access to. So I put this aside for now with the intention of coming back to it, after GCC fully supports stacktrace.

2024-08-13 15:01 UTC, crud89 commented
I've tested compiling this on my side for now and it works fine. I took the liberty to fix the target triplets and remove an obsolete warning from the build script. x64 builds run through successfully for me. Interestingly, it appears that issue #136 is resolved by this PR, though I am not sure if it's due to the drive-by changes or if it hints to some invalid code generation on the MSVC side yet.

However, I couldn't get x86 builds to compile, probably due to my lack of knowledge (I haven't touched clang much before). I have built everything from console, so vcvars must be setup properly (even when building with MSVC). However after this I am no longer able to configure the project. I will give this another try later. In the meantime, could you maybe see if you get it working? Is there anything we need to document with regards to cross-compiling using clang? And does this also affect CI?

2024-08-13 15:15 UTC, Tractorou24 commented
No problem for the delay! We all have other things to do!  
I will try the x86 builds as soon as possible, I don't remember manually testing them, thinking the CI would do the job... And I was wondering why you even support an outdated cpu architecture?  
I think we should test clang builds on CI like MSVC, since one can build but not the other. 

Regarding Linux, it seems gcc14 added full support for [std::stacktrace](https://en.cppreference.com/w/cpp/compiler_support/23)  
Il you push your branch as is, I can take a look at it (I don't promise anything about the delay)...

2024-08-13 16:00 UTC, Tractorou24 commented
I found out why it was not building in x86. 2 main reasons so far:
- size_t type is not the same as 0ull in 32bit mode, which leads to an ambiguous ctor
- the implementation of the msvc generator (copied by hand) produces a sort of internal compiler error in 32bit.

The error looks like this:
```
E:\Dev\LiteFX\src\EXEC : fatal error : error in backend: failed to perform tail call elimination on a call site marked musttail
  PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
  Stack dump:
  0.	Program arguments: C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -DLiteFX_Backends_Vulkan_EXPORTS -DSPDLOG_COMPILED_LIB -DSPDLOG_SHARED_LIB -DSPDLOG_USE_STD_FORMAT -IE:/Dev/LiteFX/src/Backends/Vulkan/src -IE:/Dev/LiteFX/src/Backends/Vulkan/include -IE:/Dev/LiteFX/src/Core/include -IE:/Dev/LiteFX/out/build/windows-clang-x86-debug/Core/include -IE:/Dev/LiteFX/src/Math/include -IE:/Dev/LiteFX/src/Rendering/include -IE:/Dev/LiteFX/src/Graphics/include -IE:/Dev/LiteFX/src/Logging/include -IE:/Dev/LiteFX/src/AppModel/include -IE:/Dev/LiteFX/src/Backends/DirectX12/include -isystem E:/Dev/LiteFX/out/build/windows-clang-x86-debug/vcpkg_installed/x86-windows/include -isystem E:/Dev/LiteFX/out/build/windows-clang-x86-debug/vcpkg_installed/x86-windows/include/directxmath -isystem E:/Dev/LiteFX/out/build/windows-clang-x86-debug/vcpkg_installed/x86-windows/include/vma -isystem E:/Dev/LiteFX/out/build/windows-clang-x86-debug/vcpkg_installed/x86-windows/include/spirv-reflect -isystem E:/Dev/LiteFX/out/build/windows-clang-x86-debug/vcpkg_installed/x86-windows/include/directx-dxc --target=i686-pc-windows-msvc -fdiagnostics-absolute-paths -O0 -g -Xclang -gcodeview -std=gnu++23 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT Backends/Vulkan/CMakeFiles/LiteFX.Backends.Vulkan.dir/src/queue.cpp.obj -MF Backends\\Vulkan\\CMakeFiles\\LiteFX.Backends.Vulkan.dir\\src\\queue.cpp.obj.d -o Backends/Vulkan/CMakeFiles/LiteFX.Backends.Vulkan.dir/src/queue.cpp.obj -c E:/Dev/LiteFX/src/Backends/Vulkan/src/queue.cpp
  1.	<eof> parser at end of file
  2.	Code generation
  3.	Running pass 'Function Pass Manager' on module 'E:/Dev/LiteFX/src/Backends/Vulkan/src/queue.cpp'.
  4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@"??R<lambda_4>@?0??submit@VulkanQueue@Backends@Rendering@LiteFX@@UBE_KABV?$Enumerable@V?$shared_ptr@$$CBVVulkanCommandBuffer@Backends@Rendering@LiteFX@@@std@@@5@@Z@QBE@XZ.resume"'
  Exception Code: 0xE0000046
   #0 0x00007fff7ad5f39c (C:\WINDOWS\System32\KERNELBASE.dll+0x5f39c)
   #1 0x00007ff612267efa (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x26c7efa)
   #2 0x00007ff612268059 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x26c8059)
   #3 0x00007ff612173473 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x25d3473)
   #4 0x00007ff612279209 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x26d9209)
   #5 0x00007ff6120dc904 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x253c904)
   #6 0x00007ff611eecf58 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x234cf58)
   #7 0x00007ff611d41342 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x21a1342)
   #8 0x00007ff611d319bb (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x21919bb)
   #9 0x00007ff611d30a5b (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x2190a5b)
  #10 0x00007ff611c82335 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20e2335)
  #11 0x00007ff611c71f0f (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20d1f0f)
  #12 0x00007ff611c70a2b (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20d0a2b)
  #13 0x00007ff611db40c6 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x22140c6)
  #14 0x00007ff60ff5b6b9 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3bb6b9)
  #15 0x00007ff611c4472e (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20a472e)
  #16 0x00007ff611c65533 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20c5533)
  #17 0x00007ff60fee6111 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x346111)
  #18 0x00007ff60fee5bdd (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x345bdd)
  #19 0x00007ff60fedfa69 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x33fa69)
  #20 0x00007ff611c60365 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20c0365)
  #21 0x00007ff61201f1a8 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x247f1a8)
  #22 0x00007ff6101517e1 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5b17e1)
  #23 0x00007ff610151282 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5b1282)
  #24 0x00007ff61014dfb4 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5adfb4)
  #25 0x00007ff61014bb30 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5abb30)
  #26 0x00007ff61014a4fe (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5aa4fe)
  #27 0x00007ff610f5e4cd (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x13be4cd)
  #28 0x00007ff6102dbc05 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x73bc05)
  #29 0x00007ff6102dba08 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x73ba08)
  #30 0x00007ff60ff8f6e8 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3ef6e8)
  #31 0x00007ff60ff8f09e (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3ef09e)
  #32 0x00007ff60ff8ebb7 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3eebb7)
  #33 0x00007ff60ff88a47 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3e8a47)
  #34 0x00007ff60ff860c3 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3e60c3)
  #35 0x00007ff6120a4b70 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x2504b70)
  #36 0x00007fff7bcb257d (C:\WINDOWS\System32\KERNEL32.DLL+0x1257d)
  #37 0x00007fff7d6caf28 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5af28)
E:\Dev\LiteFX\src\clang++ : error : clang frontend command failed with exit code 70 (use -v to see invocation)
  clang version 18.1.8
  Target: i686-pc-windows-msvc
  Thread model: posix
  InstalledDir: C:\PROGRA~1\LLVM\bin
  clang++: note: diagnostic msg: 
  ********************
  
  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
  
  Preprocessed source(s) and associated run script(s) are located at:
  clang++: note: diagnostic msg: C:\Users\DIRECT~1\AppData\Local\Temp\queue-95abd4.cpp
  clang++: note: diagnostic msg: C:\Users\DIRECT~1\AppData\Local\Temp\queue-95abd4.sh
```

So, here are the solutions I think about:
- Fix the implementation of the generator (may be really hard)
- Remove usage of generators (sad)
- Not support 32bit for clang

I'm more and more curious why you are supporting 32bit despite all bugs and extra work it can cause, for not much benefit I think.
Your commit fixing the triplets is now merged in the one adding the presets in the first place.

2024-08-14 08:52 UTC, crud89 commented
Thanks for checking. 🙂 I can repro the same issue and I think I've encountered this before. Somehow coroutines break codegen for x86 builds. This even happened on some occasions with MSVC, but I thought I fixed all of them. Still I am not sure if this is undefined behaviour or a compiler issue. It's a bit strange that this only affects x86 release builds, though. 

Anyway, I believe this will fix itself in the future, as I plan to replace `Enumerable` with `std::generator` (in #119, which is currently a mess to merge). I really hope it will be available in STL in the no so far future, so I can get back to working on this change. In the meantime I am fine with having broken x86 support when it comes to clang, however we should document it in a follow-up issue. Maybe we can drop support in the future, but I am undecided on this. I don't have any reasons not to support it yet, so I'd still prefer to have it.

Regarding stacktrace in GCC - there's partial support. You still have to link the libc++exp lib manually, which I wasn't able to get to work (at least in WSL using Ubuntu 24). It's not high on my priority list, but it's there.

2024-08-14 18:02 UTC, Tractorou24 commented
I think I will remove clang x86 presets, so it can't be broken... 
I didn't know about the sz suffix, feel free to add the comment during the review!

2024-08-16 08:38 UTC, crud89 commented on src/AppModel/include/litefx/app.hpp
> +		static AppBuilder build(TArgs&&... _args);
Should we add `[[nodiscard]]`?

2024-08-16 09:02 UTC, crud89 commented on src/Backends/DirectX12/src/descriptor_set.cpp
> +            default: break;
How do you feel about throwing a `RuntimeException` for the cases currently commented out and use `std::unreachable` for the default case?

2024-08-16 09:11 UTC, crud89 commented on src/Backends/Vulkan/src/device.cpp
> +PFN_vkCmdDrawMeshTasksEXT vkCmdDrawMeshTasks;
Any reason not to explicitly initialize those with `nullptr` here?

2024-08-16 09:12 UTC, crud89 commented on src/Backends/Vulkan/src/factory.cpp
> +		break;
I guess we can also throw an `InvalidArgumentException` here.

2024-08-16 09:18 UTC, crud89 commented on src/Rendering/include/litefx/rendering.hpp
> +        virtual const descriptor_layout_type& descriptor(UInt32 binding) const override = 0;
`override` implies `virtual`, so we should remove `virtual` from those instances (following the [core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#Rh-override) here).

2024-08-16 09:48 UTC, crud89 commented on src/Backends/DirectX12/include/litefx/backends/dx12.hpp
> +
Instead of implementing those methods here again, turn the inheritances of `Pipeline` in `ComputePipeline`, `RenderPipeline` and `RayTracingPipeline` `virtual`, too. This should result in the functions being mapped to a single implementation in the vtable.

For example:

```cxx
// rendering_api.hpp

template <typename TPipelineLayout, typename TShaderProgram>
class ComputePipeline : public IComputePipeline, public virtual Pipeline<TPipelineLayout, TShaderProgram> {
public:
    virtual ~ComputePipeline() noexcept = default;
};
```

2024-08-16 09:53 UTC, crud89 requested changes
I've got some minor nitpicks, but overall this looks good to me. If you resolve the changes, I am happy to merge the PR. As discussed, please also remove the x86 clang presets (we'll create a follow-up issue after the PR is merged) and document this in the readme (e.g. clang (x64 only)). Regarding the `size_t` literal, you don't need to change anything just yet. It isn't supported in MSVC yet and will only be required for working x86 builds in the future. I will test the CI changes in a private repo and update them later. Thanks again! ☺

2024-08-16 19:11 UTC, Tractorou24 commented
I think l will make the changes next week when I have time to ! Thanks for your review !

2024-08-23 16:10 UTC, Tractorou24 commented on src/Rendering/include/litefx/rendering.hpp
> +        virtual const descriptor_layout_type& descriptor(UInt32 binding) const override = 0;
I don't think that's what the guideline says.  
It says:
```
virtual means exactly and only “this is a new virtual function.”
override means exactly and only “this is a non-final overrider.”
final means exactly and only “this is a final overrider.”
```

Here, it is a new virtual function masking the parent one, due to the change in return type (which is not covariant).

2024-08-23 19:29 UTC, Tractorou24 commented on src/Rendering/include/litefx/rendering.hpp
> +        virtual const descriptor_layout_type& descriptor(UInt32 binding) const override = 0;
I removed them everywhere I found them in the codebase in a separate commit.

2024-08-23 19:30 UTC, Tractorou24 commented on src/Backends/DirectX12/include/litefx/backends/dx12.hpp
> +
Nice catch! It's so much better like that! Didn't find it like this at first...

2024-08-23 19:36 UTC, Tractorou24 commented
I squashed your doc commit and fixed all review comments.  
If you have anything else, you can add a comment and I will take care of it!

2024-08-26 08:22 UTC, crud89 approved these changes

2024-08-26 08:24 UTC, crud89 commented
LGTM! I've fixed some places where indentation got too deep (probably caused by [this issue](https://developercommunity.visualstudio.com/t/10434699)). I am going to merge the PR and check if the builds are successful. If so I will include clang to build in weekly builds as well as (future) test and release builds (#129).

Thank you! 🙂

2024-08-26 08:24 UTC, merged