Support linux using GCC-14
crud89/LiteFX pull request #140
Opened 2024-09-13 20:22 UTC by Tractorou24

**Describe the pull request**
Adds support for linux (tested on WSL Ubuntu 24.04), using the gcc14.2 compiler (built from source).  
It also adds support for the uz suffix in MSVC, which was one requirement to unblock #139.

It is based & contains big parts the linux branch you pushed in the repo.

**Related issues**
None.

2024-09-14 10:08 UTC, crud89 commented
Thanks for the PR. I'm currently on vacation, so I cannot review it. I will get back to it when I'm back home at the end of September. 🙂

2024-09-15 16:38 UTC, Tractorou24 commented
No problem. Have a good vacation!

2024-10-16 11:52 UTC, crud89 requested changes
Thanks again for the PR! There are just some minor issues, but apart from that, I got everything working on my machine. Just for completeness, here's how I compiled gcc 14.2:

```sh
sudo apt install build-essential
sudo apt install libmpfr-dev libgmp3-dev libmpc-dev -y
wget http://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz
tar -xf gcc-14.2.0.tar.gz
cd gcc-14.2.0
./configure -v --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --prefix=/usr/local/gcc-14.2.0 --enable-libstdcxx-backtrace --enable-checking=release --enable-languages=c,c++ --disable-multilib --program-suffix=-14.2.0
make
sudo make install
sudo update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-14.2.0/bin/g++14.2.0 14
sudo update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-14.2.0/bin/gcc14.2.0 14
```

And the same for DXC:

```sh
mkdir dxc && cd ./dxc/
wget https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2407/linux_dxc_2024_07_31.x86_64.tar.gz
sudo mkdir /usr/local/dxc
sudo tar -xf linux_dxc_2024_07_31.x86_64.tar.gz -C /usr/local/dxc/
sudo update-alternatives --install /usr/bin/dxc dxc /usr/local/dxc/bin/dxc 2024
```

Regarding the PR, I think we could also add overlay triplets for vcpkg, similar to the windows ones, so that release builds don't build debug dependencies.

As for full Linux support, I think there are two major issues left, that could be followed up in separate PRs:
- We need to find a proper replacement for `<codecvt>` (as noted for *string.hpp*)
- CI scripts need runners with builtin support for a later version of GCC, that does not need to be self-compiled (mainly due to the `stdc++exp` dependency). Maybe we can remove the stacktrace dependency using a build option in the meantime, however currently Ubuntu runner images only ship with gcc 13.2 anyway.

2024-10-16 11:52 UTC, crud89 commented on src/Backends/Vulkan/src/buffer.cpp
> +	std::memcpy(reinterpret_cast<void*>(buffer + (element * this->alignedElementSize())), data, size);
I'm note sure if we should do this change. Does `std::memcpy` do bounds checking?

2024-10-16 11:52 UTC, crud89 commented on src/Backends/Vulkan/src/buffer.cpp
> +    std::memcpy(data, reinterpret_cast<void*>(buffer + (element * this->alignedElementSize())), size);
The copies must be selected based on the `write` parameter. First call writes, the second one reads from the buffer.

2024-10-16 11:52 UTC, crud89 commented on src/Core/CMakeLists.txt
> +
This can be removed, doesn't it? GCC needs to be compiled with this flag enabled, but the engine does not, if I am not mistaken.

2024-10-16 11:52 UTC, crud89 commented on src/Core/include/litefx/string.hpp
If we fully want to support Linux, we should ultimately replace `<codecvt>`. Currently this is fine, but we need to fix this in a follow-up issue. [uni-algo](https://github.com/uni-algo/uni-algo) does provide a header only library for those conversions, but I am also open for alternatives. 🙂

2024-11-05 13:07 UTC, crud89 commented
I've pushed some changes to the development branch and changed the base to a new feature branch, so that we can continue development there for the time being. I want to have tests and CI running before merging this into the main branch.

Before closing the PR through, I want to double check if we broke any Windows builds and also I want to add proper overlay triplets for the Linux platform.

2024-11-06 14:37 UTC, merged

2024-11-06 14:50 UTC, crud89 commented
I've pushed some more changes and ensured that everything still works under Windows. Follow-up tracking issue is linked above. I'll see if I can port some of the organizational changes to the main branch when I find time for it. Thanks again for taking the time and working on this! 😊

2024-11-06 21:00 UTC, Tractorou24 commented
Thank you very much for your changes! I'll try to continue and get some things you wrote in the issue done when I have some time, which is currently quite hard to find...